enyo.depends(
  "Wig.js",
  "Wig.css",
  "enyo/Plugin.js",
  "enyo/CartList.js",
  "enyo/CartDetail.js",
  "enyo/GameMain.js",
  "enyo/GameMain.ActionRow.js",
  "enyo/GameMain.List.js",
  "enyo/GameMain.Detail.js",
  "enyo/GameMain.HomeScreen.js",
  "enyo/Messages.js",
  "enyo/Preferences.js",
  "enyo/Main.js",
  "enyo/Utils.js",
  "enyo/Waypoint.js",
  "enyo/Help.js"
);
